# site properties and page defaults
title: 서울대학교 심리과학연구소
subtitle: Institute of Psychological Science
description: 서울대학교 심리과학연구소는 행동과학, 뇌과학, 임상심리, 데이터 과학을 통합하여 인간의 심리와 사회적 문제를 연구합니다.
url: "https://snu-psych-science.github.io"
baseurl: ""
lang: ko-KR
header: images/background.png
footer: images/background.png
logo: images/logo_.png
icon: images/icon.png
share_image: images/share.png
# shared institute contact information
contact:
  email: ips.snu@gmail.com
  address_lines:
    - 서울대학교 사회과학대학
    - 서울특별시 관악구 관악로 1 16동

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # event documents
  - scope:
      type: "events"
    values:
      layout: event
  # newsletter documents
  - scope:
      type: "newsletters"
    values:
      layout: newsletter
  # notice documents
  - scope:
      type: "notices"
    values:
      layout: notice

collections:
  events:
    output: true
    permalink: /events/:name/
    
  newsletters:
    output: true
    permalink: /newsletters/:name/
    
  notices:
    output: true
    permalink: /notices/:name/

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles
  style: compressed

# force jekyll to include certain files/folders
include:
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - .github
  - .node-version
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.md
  - package.json
  - package-lock.json
  - tests
  - node_modules
  - tmp
  - vendor
