# site properties and page defaults
title: 서울대학교 심리과학연구소
subtitle: Institute of Psychological Science
description: 서울대학교 심리과학연구소는 행동과학, 뇌과학, 임상심리, 데이터 과학을 통합하여 인간의 심리와 사회적 문제를 연구합니다.
header: images/background.png
footer: images/background.png
proofer: false

# site social media and other links
links:
  email: ips.snu@gmail.com

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

  events:
    output: true
    permalink: /events/:name/
    
  newsletters:
    output: true
    permalink: /newsletters/:name/

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
