name: on-push
run-name: on push to main

on:
  push:
    branches:
      - main

  # run if user manually requests it
  workflow_dispatch:

concurrency:
  group: live-main-build
  cancel-in-progress: true

jobs:
  test-site:
    permissions:
      contents: read
    uses: ./.github/workflows/test-site.yaml
    with:
      baseurl: ""
      artifact_name: live-site-${{ github.sha }}

  build-site:
    needs: test-site
    permissions:
      contents: write
      actions: read
    uses: ./.github/workflows/build-site.yaml
    with:
      artifact_name: live-site-${{ github.sha }}
