name: on-pull-request
run-name: on pull request activity

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

permissions:
  contents: read

jobs:
  test-site:
    if: github.event.action != 'closed'
    uses: ./.github/workflows/test-site.yaml

  build-preview:
    needs: test-site
    if: >-
      always() &&
      github.event.pull_request.head.repo.full_name == github.repository &&
      github.actor != 'dependabot[bot]' &&
      (github.event.action == 'closed' || needs.test-site.result == 'success')
    permissions:
      contents: write
      pull-requests: write
    uses: ./.github/workflows/build-preview.yaml
