name: on-pull-request
run-name: on pull request activity

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency:
  group: preview-pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  test-site:
    if: github.event.action != 'closed'
    permissions:
      contents: read
    uses: ./.github/workflows/test-site.yaml
    with:
      baseurl: /preview/pr-${{ github.event.pull_request.number }}
      artifact_name: preview-pr-${{ github.event.pull_request.number }}-${{ github.event.pull_request.head.sha }}

  build-preview:
    needs: test-site
    if: >-
      always() &&
      github.event.pull_request.head.repo.full_name == github.repository &&
      github.actor != 'dependabot[bot]' &&
      (github.event.action == 'closed' || needs.test-site.result == 'success')
    permissions:
      contents: write
      actions: read
      pull-requests: read
    uses: ./.github/workflows/build-preview.yaml
    with:
      artifact_name: preview-pr-${{ github.event.pull_request.number }}-${{ github.event.pull_request.head.sha }}
